// Mocks generated by Mockito 5.4.6 from annotations
// in mabquiz/test/features/quiz/application/providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mabquiz/src/features/quiz/application/quiz_service.dart' as _i2;
import 'package:mabquiz/src/features/quiz/data/models/question.dart' as _i5;
import 'package:mabquiz/src/features/quiz/data/repositories/quiz_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQuizScore_0 extends _i1.SmartFake implements _i2.QuizScore {
  _FakeQuizScore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [QuizRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizRepository extends _i1.Mock implements _i3.QuizRepository {
  MockQuizRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i3.QuizSessionData?> get quizSessionStream =>
      (super.noSuchMethod(
            Invocation.getter(#quizSessionStream),
            returnValue: _i4.Stream<_i3.QuizSessionData?>.empty(),
          )
          as _i4.Stream<_i3.QuizSessionData?>);

  @override
  _i4.Future<List<_i5.Question>> getQuestionsBySubject(String? subject) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionsBySubject, [subject]),
            returnValue: _i4.Future<List<_i5.Question>>.value(<_i5.Question>[]),
          )
          as _i4.Future<List<_i5.Question>>);

  @override
  _i4.Future<List<_i5.Question>> getQuestionsByDifficulty(
    _i5.DifficultyLevel? difficulty,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionsByDifficulty, [difficulty]),
            returnValue: _i4.Future<List<_i5.Question>>.value(<_i5.Question>[]),
          )
          as _i4.Future<List<_i5.Question>>);

  @override
  _i4.Future<List<_i5.Question>> getRandomQuestions({
    int? limit = 10,
    String? subject,
    _i5.DifficultyLevel? difficulty,
    List<String>? excludeIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomQuestions, [], {
              #limit: limit,
              #subject: subject,
              #difficulty: difficulty,
              #excludeIds: excludeIds,
            }),
            returnValue: _i4.Future<List<_i5.Question>>.value(<_i5.Question>[]),
          )
          as _i4.Future<List<_i5.Question>>);

  @override
  _i4.Future<_i5.Question?> getQuestionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionById, [id]),
            returnValue: _i4.Future<_i5.Question?>.value(),
          )
          as _i4.Future<_i5.Question?>);

  @override
  _i4.Future<List<String>> getAvailableSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableSubjects, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);
}

/// A class which mocks [QuizService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizService extends _i1.Mock implements _i2.QuizService {
  MockQuizService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i3.QuizSessionData?> get quizSessionStream =>
      (super.noSuchMethod(
            Invocation.getter(#quizSessionStream),
            returnValue: _i4.Stream<_i3.QuizSessionData?>.empty(),
          )
          as _i4.Stream<_i3.QuizSessionData?>);

  @override
  _i4.Future<List<_i5.Question>> getQuizQuestions({
    int? limit = 10,
    String? subject,
    _i5.DifficultyLevel? difficulty,
    List<String>? excludeIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getQuizQuestions, [], {
              #limit: limit,
              #subject: subject,
              #difficulty: difficulty,
              #excludeIds: excludeIds,
            }),
            returnValue: _i4.Future<List<_i5.Question>>.value(<_i5.Question>[]),
          )
          as _i4.Future<List<_i5.Question>>);

  @override
  _i4.Future<List<_i5.Question>> getQuestionsBySubject(String? subject) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionsBySubject, [subject]),
            returnValue: _i4.Future<List<_i5.Question>>.value(<_i5.Question>[]),
          )
          as _i4.Future<List<_i5.Question>>);

  @override
  _i4.Future<List<_i5.Question>> getQuestionsByDifficulty(
    _i5.DifficultyLevel? difficulty,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionsByDifficulty, [difficulty]),
            returnValue: _i4.Future<List<_i5.Question>>.value(<_i5.Question>[]),
          )
          as _i4.Future<List<_i5.Question>>);

  @override
  _i4.Future<_i5.Question?> getQuestionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionById, [id]),
            returnValue: _i4.Future<_i5.Question?>.value(),
          )
          as _i4.Future<_i5.Question?>);

  @override
  _i4.Future<List<String>> getAvailableSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableSubjects, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i2.QuizScore calculateScore(
    List<_i5.Question>? questions,
    Map<String, String>? answers,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateScore, [questions, answers]),
            returnValue: _FakeQuizScore_0(
              this,
              Invocation.method(#calculateScore, [questions, answers]),
            ),
          )
          as _i2.QuizScore);
}
